export const combatTypes = {
  START:'START',
  DODGED: 'DODGED',
  HIT: 'HIT',
  MISSED: 'MISSED',
  DEFLECTED: 'DEFLECTED',
  RETALIATED: 'RETALIATED',
  CHARACTERDIED: 'CHARACTERDIED',
  MONSTERDIED: 'MONSTERDIED',
  FLEE: 'FLEE',
  FLEE_FAIL: 'FLEE_FAIL',
}