export const locationTypes = {
  TRAINING_GROUNDS: "TRAINING_GROUNDS",
  WOODS: 'WOODS',
  CASTLE: 'CASTLE',
  CASTLE_YARD: 'CASTLE_YARD',
  CASTLE_GATE: 'CASTLE_GATE',
  CASTLE_HALL: 'CASTLE_HALL',
  DUNGEON: 'DUNGEON',
  CAVE: 'CAVE',
  ROOM: 'ROOM',
};
