export const stageTypes = {
  IDLE: "IDLE",
  TRACK: "TRACK",
  COMBAT: "COMBAT",
  TRACK_RESOURCE: "TRACK_RESOURCE",
  TRACK_COMBAT: "TRACK_COMBAT",
  COMBAT_DEATH: 'COMBAT_DEATH',
  COMBAT_WIN: 'COMBAT_WIN',
  COMBAT_WIN_DROP: 'COMBAT_WIN_DROP',
  COMBAT_FLEE: 'COMBAT_FLEE',
  SHOP: 'SHOP',
};
